src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomProduit;

    /**
     * @ORM\Column(type="float")
     */
    private $prixProduit;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantiteProduit;

    /**
     * @ORM\Column(type="float")
     */
    private $poidsProduit;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $DescriptionProduit;

    /**
     * @ORM\ManyToMany(targetEntity=Ingredient::class, inversedBy="Produits")
     */
    private $Ingredients;

    /**
     * @ORM\ManyToMany(targetEntity=Commande::class, mappedBy="Produits")
     */
    private $commandes;

    /**
     * @ORM\OneToOne(targetEntity=Image::class, mappedBy="Produits", cascade={"persist", "remove"})
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Categorie;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageProduit;

    public function __construct()
    {
        $this->Ingredients = new ArrayCollection();
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomProduit(): ?string
    {
        return $this->nomProduit;
    }

    public function setNomProduit(string $nomProduit): self
    {
        $this->nomProduit = $nomProduit;

        return $this;
    }

    public function getPrixProduit(): ?float
    {
        return $this->prixProduit;
    }

    public function setPrixProduit(float $prixProduit): self
    {
        $this->prixProduit = $prixProduit;

        return $this;
    }

    public function getQuantiteProduit(): ?int
    {
        return $this->quantiteProduit;
    }

    public function setQuantiteProduit(int $quantiteProduit): self
    {
        $this->quantiteProduit = $quantiteProduit;

        return $this;
    }

    public function getPoidsProduit(): ?float
    {
        return $this->poidsProduit;
    }

    public function setPoidsProduit(float $poidsProduit): self
    {
        $this->poidsProduit = $poidsProduit;

        return $this;
    }

    public function getDescriptionProduit(): ?string
    {
        return $this->DescriptionProduit;
    }

    public function setDescriptionProduit(?string $DescriptionProduit): self
    {
        $this->DescriptionProduit = $DescriptionProduit;

        return $this;
    }

    /**
     * @return Collection|Ingredient[]
     */
    public function getIngredients(): Collection
    {
        return $this->Ingredients;
    }

    public function addIngredient(Ingredient $ingredient): self
    {
        if (!$this->Ingredients->contains($ingredient)) {
            $this->Ingredients[] = $ingredient;
        }

        return $this;
    }

    public function removeIngredient(Ingredient $ingredient): self
    {
        $this->Ingredients->removeElement($ingredient);

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->addProduit($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            $commande->removeProduit($this);
        }

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(Image $image): self
    {
        // set the owning side of the relation if necessary
        if ($image->getProduits() !== $this) {
            $image->setProduits($this);
        }

        $this->image = $image;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->Categorie;
    }

    public function setCategorie(string $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    public function getImageProduit(): ?string
    {
        return $this->imageProduit;
    }

    public function setImageProduit(?string $imageProduit): self
    {
        $this->imageProduit = $imageProduit;

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nomProduit')
            ->add('prixProduit')
            ->add('quantiteProduit')
            ->add('poidsProduit')
            ->add('DescriptionProduit')
            ->add('Ingredients')
            ->add('commandes')
            ->add('imageProduit')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/produits")
 */
class ProduitController extends AbstractController
{
    /**
     * @Route("/", name="produit_index", methods={"GET"})
     */
    public function index(ProduitRepository $produitRepository): Response
    {
        return $this->render('produit/index.html.twig', [
            'produits' => $produitRepository->findAll(),
        ]);
    }


    /**
     * @Route("/new", name="produit_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($produit);
            $entityManager->flush();

            return $this->redirectToRoute('produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="produit_show", methods={"GET"})
     */
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="produit_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Produit $produit): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="produit_delete", methods={"POST"})
     */
    public function delete(Request $request, Produit $produit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('produit_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="button m-1" id="btn-article-create">Supprimer le produit</button>
</form>

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
    <h1>Edit Produit</h1>

    {{ include('produit/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('produit_index') }}">back to list</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos produits - LaBonneMiche{% endblock %}

{% block body %}
    <div class="container-fluid bodyhome ">
        <ul class="breadcrumb">
            <li class="href-top"><a class="href-top" href="/">Accueil</a> <span class="divider">/</span></li>
            <li class="href-top active">Produits</li>
        </ul>

        <h1 id="tltphare">Produits</h1>
        {% if is_granted('ROLE_ADMIN') %}
            <a href="https://127.0.0.1:8000/admin?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CProduitCrudController&menuIndex=1&signature=TcOv6RHT6xojuR5PqztCpPFyk9N9JZHRt-WswYmntyc&submenuIndex=-1" class="button m-3" id="btn-article-create">Créer un nouvel article</a>
        {% endif %}

        <div class="row">
            {% for produit in produits %}
                <div class="col-3 mb-2 mt-1">
                    <div class="card " style="width: 100%; height:100%;">
                        <img src="{{asset('img/produits/'~ produit.getImageProduit())}}" class="img-responsive" width="auto" height="50%">
                        <div class="card-body card-panier ">
                            <h5 class="card-title">{{ produit.nomProduit }}</h5>
                            <p class="card-text" style="color:#e3b364">{{ produit.descriptionProduit | raw }}</p>
                            <a href="{{ path('produit_show',{'id':produit.id}) }}" class="btn btn-primary mb-3" id="btnregisterlogin">Voir le produit</a>
                            {% if is_granted('ROLE_ADMIN') %}
                                <a href="{{ path('produit_edit', {'id': produit.id}) }}"  class="btn btn-primary" id="btnregisterlogin">Modifier l'article</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}
    <h1>Create new Produit</h1>

    {{ include('produit/_form.html.twig') }}

    <a href="{{ path('produit_index') }}">back to list</a>
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ produit.nomProduit }} - LaBonneMiche{% endblock %}

{% block body %}




<div class="bodyhome">
    <ul class="breadcrumb">
        <li><a class="href-top" href="/">Accueil</a> <span class="divider">/</span></li>
        <li><a class="href-top" href="/produits">Produits</a> <span class="divider">/</span></li>
        <li class="href-top active">{{ produit.nomProduit }}</li>
    </ul>
<br>
    <div class="container ">
        <div class="card">
            <div class="card-body card-panier ">
                <div class="row">
                    <div class="col-lg-5 col-md-5 col-sm-6">
                        <div class="white-box text-center"><img src="{{asset('img/produits/'~ produit.getImageProduit())}}" class="img-responsive"></div>
                    </div>
                    <div class="col-lg-7 col-md-7 col-sm-6">
                        <h3 class="card-title text-center m-2 card-title-produit">{{ produit.nomProduit }}</h3>
                        <h6 class="card-subtitle text-center mb-5 card-text card-categorie">{{ produit.categorie }}</h6>
                        <p class="text-center card-description">{{ produit.descriptionProduit|raw }}</p>
                        <h2 class="mt-5 card-description">
                            {{ produit.prixProduit }}<small class="text-success"></small>€
                        </h2>

                        {% if app.user %}
                           <a id="btn-panier-acheter" class="btn btn-primary" href="{{ path('panier_add',{'id':produit.id}) }}">Ajouter au panier</a>
                        {% else %}
                            <a id="btn-panier-acheter" class="btn btn-primary"  href="{{ path('app_login')}}">Ajouter au panier</a>
                        {% endif %}




                    </div>
                    {% if is_granted('ROLE_ADMIN') %}
                        <a href="{{ path('produit_edit', {'id': produit.id}) }}" class="button m-3" id="btn-article-create">Modifier le produit</a>
                        {{ include('produit/_delete_form.html.twig') }}
                    {% endif %}
                    <a  id="buttonHeader" class="btn-back-produit"onclick="location.href='/produits'" role="button">Revenir aux produits</a>

                </div>
            </div>
        </div>
    </div>

<br>

</div>





{% endblock %}